openapi: 3.0.2
info:
  title: 'API NODO-SPC: Configurazioni dei PSP'
  version: 0.0.1
  description: ''
  termsOfService: 'http://swagger.io/terms/'
  x-logo:
    url: ''
servers:
  - url: 'https://{env}/rest/configs/{version}'
    description: 'Endpoint URL'
    variables:
      env:
        default: api.nodospc.pagopa.gov.it
        enum:
          - 'api.nodospc.pagopa.gov.it' #PROD
          - 'test-api.nodospc.pagopa.gov.it' #UAT
          - 'sit-api.nodospc.pagopa.gov.it' #SIT
      version:
        default: v0
        description: Versione della API NODO-SPC
paths:
  /psps:
    summary: Operazioni su collection di risorse di tipo “PSP”
    get:
      tags:
        - psps
      parameters:
        - $ref: '#/components/parameters/NODOSPC-API-Version'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionPsp'
          headers:
            X-RateLimit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
          description: OK
        '429':
          $ref: '#/components/responses/429'
        'default':
          $ref: '#/components/responses/default'
      operationId: getCollectionPsp
      summary: Get collection di risorse di tipo “PSP”
  /psps/{idPsp}:
    summary: Operazioni su risorsa di tipo “PSP”
    get:
      tags:
        - psps
      parameters:
        - $ref: '#/components/parameters/idPsp'
        - $ref: '#/components/parameters/NODOSPC-API-Version'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Psp'
          headers:
            X-RateLimit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
          description: OK
        '429':
          $ref: '#/components/responses/429'
        'default':
          $ref: '#/components/responses/default'
      operationId: getPsp
      summary: Get risorsa di tipo “PSP”
  /psps/{idPsp}/canali-versamento:
    summary: Operazioni su sub-collection di risorse di tipo “PspCanaleVersamento”
    get:
      tags:
        - psps
      parameters:
        - $ref: '#/components/parameters/idPsp'
        - $ref: '#/components/parameters/NODOSPC-API-Version'
      responses:
        '200':
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/SubCollectionPspCanaleVersamento'
          headers:
            X-RateLimit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
          description: OK
        '429':
          $ref: '#/components/responses/429'
        'default':
          $ref: '#/components/responses/default'
      operationId: getSubCollectionPspCanaleVersamento
      summary: Get sub-collection di risorse di tipo “PspCanaleVersamento”
  /psps/{idPsp}/canali-versamento/{idRes}:
    summary: Operazioni su risorsa di tipo “PspCanaleVersamento”
    get:
      tags:
        - psps
      parameters:
        - $ref: '#/components/parameters/idPsp'
        - $ref: '#/components/parameters/idRes'
        - $ref: '#/components/parameters/NODOSPC-API-Version'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubPspCanaleVersamento'
          headers:
            X-RateLimit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
          description: OK
        '429':
          $ref: '#/components/responses/429'
        'default':
          $ref: '#/components/responses/default'
      operationId: gePspCanaleVersamentoByIdPsp
      summary: >-
        Get risorsa di tipo “PspCanaleVersamento” di un "PSP"
  /canali-versamento:
    summary: Operazioni su collection di risorse di tipo “CanaleVersamento”
    get:
      tags:
        - canali-versamento
      parameters:
        - name: 'idPsp'
          description: Identificativo univoco risorsa "PSP"
          schema:
            type: string
          in: query
          required: false
        - $ref: '#/components/parameters/NODOSPC-API-Version'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionPspCanaleVersamento'
          headers:
            X-RateLimit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
          description: OK
        '429':
          $ref: '#/components/responses/429'
        'default':
          $ref: '#/components/responses/default'
      operationId: geCollectionPspCanaleVersamento
      summary: >-
        Get collection di risorse di tipo “PspCanaleVersamento”
  /canali-versamento/{idRes}:
    summary: Operazioni su risorsa di tipo “PspCanaleVersamento”
    get:
      tags:
        - canali-versamento
      parameters:
        - $ref: '#/components/parameters/idRes'
        - $ref: '#/components/parameters/NODOSPC-API-Version'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PspCanaleVersamento'
          headers:
            X-RateLimit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
          description: OK
        '429':
          $ref: '#/components/responses/429'
        'default':
          $ref: '#/components/responses/default'
      operationId: gePspCanaleVersamento
      summary: >-
        Get risorsa di tipo “PspCanaleVersamento”
components:
  schemas:
    AllowedMethods:
      type: string
      enum:
        - 'GET'
        - 'HEAD'
        - 'POST'
        - 'PUT'
        - 'DELETE'
    Link:
      type: object
      properties:
        rel:
          type: string
          enum:
            - 'self'
            - 'canali-versamento'
        href:
          type: string
          format: uri
        type:
          type: array
          items:
            $ref: '#/components/schemas/AllowedMethods'
      example: 
        rel:  "self"
        href: "/path-to-resource/1234"
        type: "['GET' , 'POST']"
      description: Link generico
    LinkRisorsa:
      type: object
      properties:
        uri:            
          $ref: '#/components/schemas/Link'
      required:
        - uri
      example: 
        uri:
          rel:  "self"
          href: "/path-to-resource/1234"
          type: "['GET']"
      description: Link a risorsa generica
    Risorsa:
      type: object
      allOf:
        - $ref: '#/components/schemas/LinkRisorsa'
      properties:
        idRes:
          type: string
          description: Identificativo univoco della risorsa
      required:
        - idRes
      example: 
        uri:
          rel:  "self"
          href: "/path-to-resource/1234"
          type: "['GET']"
        idRes: '1234'
      description: Risorsa generica
    CollectionPsp:
      type: object
      properties:
        uri:            
          $ref: '#/components/schemas/Link'
        resources:
          type: array
          items:
            $ref: '#/components/schemas/LinkPsp'
      required:
        - uri
        - resources
      example:
        uri: 
          rel: "self"
          href: "/psps"
          type: ["GET"]
        resources: [{"rel": "psps","href": "/psps/1000","type": ['GET']},{"rel": "psps","href": "/psps/1001","type": ['GET']}]
      description: Collection di risorse di tipo "PSP"
    LinkPsp:
      description: Link a risorsa di tipo "PSP"
      allOf:
        - $ref: '#/components/schemas/LinkRisorsa'
      example: 
        uri: 
          rel: "psps"
          href: "/psps/1000"
          type: ["GET"]
    Psp:
      description: >-
        Risorsa che rappresenta un "PSP"
      allOf:
        - $ref: '#/components/schemas/Risorsa'
        - type: object
          properties:
            idPsp:
              type: string
            ragioneSociale:
              type: string
            links:       
              $ref: '#/components/schemas/SubCollectionPspCanaleVersamento'
      example: 
        uri: 
          rel: "self"
          href: "/psps/1000"
          type: ["GET"]
        idRes: "1234"
        idPsp: "1000"
        ragioneSociale: "Ragione Sociale del PSP"
        links: [{"rel": "psp/canali-versamento","href": "/psps/1000/canali-versamento/2000","type": ['GET']},{"rel": "psp/canali-versamento","href": "/psps/1000/canali-versamento/2001","type": ['GET']}]
    CollectionPspCanaleVersamento:
      type: object
      properties:
        uri:            
          $ref: '#/components/schemas/Link'
        resources:
          type: array
          items:
            $ref: '#/components/schemas/LinkPspCanaleVersamento'
      required:
        - uri
        - resources
      example: 
        uri: 
          rel: "self"
          href: "/canali-versamento"
          type: ["GET"]
        resources: [{"rel": "canali-versamento","href": "/canali-versamento/2000","type": ['GET']},{"rel": "canali-versamento","href": "/canali-versamento/2001","type": ['GET']}]
      description: Collection di risorse di tipo "PSPCanaleVersamento"
    SubCollectionPspCanaleVersamento:
      type: object
      properties:
        uri:            
          $ref: '#/components/schemas/Link'
        resources:
          type: array
          items:
            $ref: '#/components/schemas/LinkSubPspCanaleVersamento'
      required:
        - uri
        - resources
      example: 
        uri: 
          rel: "self"
          href: "/psps/1000/canali-versamento"
          type: ["GET"]
        resources: [{"rel": "psp/canali-versamento","href": "/psps/1000/canali-versamento/2000","type": ['GET']},{"rel": "psp/canali-versamento","href": "/psps/1000/canali-versamento/2001","type": ['GET']}]
      description: Sub-Collection di risorse di tipo "PSPCanaleVersamento" di un "PSP"
    LinkPspCanaleVersamento:
      description: Link a risorsa di tipo "PspCanaleVersamento" nella collection
      allOf:
        - $ref: '#/components/schemas/LinkRisorsa'
      example: 
        uri:
          rel: 'canali-versamento'
          href: 'canali-versamento/2000'
          type: ['GET']
    LinkSubPspCanaleVersamento:
      description: Link a risorsa di tipo "PspCanaleVersamento" nella sub-collection di un risorsa di tipo "PSP"
      allOf:
        - $ref: '#/components/schemas/LinkRisorsa'
      example: 
        uri:
          rel: 'psp/canali-versamento'
          href: '/psps/1000/canali-versamento/2000'
          type: ['GET']
    PspCanaleVersamento:
      description: >-
        Risorsa che rappresenta un “CanaleVersamento” di un "PSP"
      allOf:
        - $ref: '#/components/schemas/Risorsa'
        - type: object
          properties:
            idPsp:
              type: string
            idIntermediarioPsp:
              type: string
            codiceIntermediarioPSp:
              type: string
            idCanale:
              type: string
            modelloPagamento:
              type: string
            tipoVersamento:
              type: string
          example:
            uri: 
              rel: 'self'
              href: '/canali-versamento/2200'
              type: ['GET']
            idRes: '2200'
            idPsp: '1000'
            idIntermediarioPsp: '3000'
            idCanale: '4000'
            modelloPagamento: 'ATTIVATO_PRESSO_PSP'
            tipoVersamento: 'AD'
    SubPspCanaleVersamento:
      description: >-
        Risorsa che rappresenta un “CanaleVersamento” nella sub-collection di una risorsa di tipo "PSP"
      allOf:
        - $ref: '#/components/schemas/Risorsa'
        - type: object
          properties:
            idPsp:
              type: string
            idIntermediarioPsp:
              type: string
            codiceIntermediarioPSp:
              type: string
            idCanale:
              type: string
            modelloPagamento:
              type: string
            tipoVersamento:
              type: string
            collectionLink:            
              $ref: '#/components/schemas/Link'
          example:
            uri: 
              rel: 'self'
              href: '/psps/1000/canali-versamento/2000'
              type: ['GET']
            idRes: '2000'
            idPsp: '1000'
            idIntermediarioPsp: '3000'
            idCanale: '4000'
            modelloPagamento: 'ATTIVATO_PRESSO_PSP'
            tipoVersamento: 'AD'
            collectionLink: 
              rel: 'canali-versamento/2200'
              href: '/canali-versamento/2200'
              type: ['GET']
    ErrorDetails:
      type: object
      properties:
        type:
          default: about:blank
          format: uri
          type: string
          description: A URI reference that identifies the problem type
          example: 'https://example.com/errors/429'
        title:
          type: string
          description: A short, human-readable summary of the problem type
          example: 'Too Many Requests'
        status:
          format: int32
          exclusiveMaximum: true
          maximum: 600
          minimum: 100
          type: integer
          description: The HTTP status code generated by the server
          example: '429'
        detail:
          type: string
          description: A human-readable explanation of the problem type    
        instance:
          format: uri
          type: string
          description: A URI reference that identifies the specific occurrence of the problem 
          example: '/resource/12345/data/abc'
      description: 'A "problem detail" as a way to carry machine-readable details of errors in a HTTP response to avoid the need to define new error response formats for HTTP APIs'
  responses:
    '429':
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ErrorDetails'
      headers:
        X-RateLimit-Limit:
          $ref: '#/components/headers/X-RateLimit-Limit'
        X-RateLimit-Remaining:
          $ref: '#/components/headers/X-RateLimit-Remaining'
        X-RateLimit-Reset:
          $ref: '#/components/headers/X-RateLimit-Reset'
        Retry-After:
          $ref: '#/components/headers/Retry-After'
      description: Risposta utilizzata nel caso di superamento del rate limit.
    'default':
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ErrorDetails'
      headers:
        X-RateLimit-Limit:
          $ref: '#/components/headers/X-RateLimit-Limit'
        X-RateLimit-Remaining:
          $ref: '#/components/headers/X-RateLimit-Remaining'
        X-RateLimit-Reset:
          $ref: '#/components/headers/X-RateLimit-Reset'
      description: Risposta di default utilizzata per tutti gli status code HTTP. 
  parameters:
    idPsp:
      name: 'idPsp'
      description: Identificativo univoco risorsa "PSP"
      schema:
        type: string
      in: path
      required: true
    idRes:
      name: 'idRes'
      description: Identificativo univoco risorsa
      schema:
        type: string
      in: path
      required: true
    NODOSPC-API-Version:
      name: 'NODOSPC-API-Version'
      description: Versione della API del sistema NODOSPC richiesta dal client. 
      in: header
      required: true
      schema:
        type: string
        example: 'v1'
  headers:
    X-RateLimit-Limit:
      description: Limite massimo di richieste nella time-box
      schema:
        format: int32
        type: integer
      example: 100
    X-RateLimit-Remaining:
      description: Numero di richieste rimanenti nella time-box fino al prossimo reset
      schema:
        format: int32
        type: integer
      example: 94
    X-RateLimit-Reset:
      description: Numero di secondi rimanenti nella time-box fino al prossimo reset
      schema:
        format: int32
        type: integer
      example: 94
    Retry-After:
      description: Indica quanti secondi attendere prima di eseguire una nuova richiesta.
      schema:
        format: int32
        type: integer
      example: 94
  securitySchemes:
    JWTAuth:
      scheme: Bearer
      type: http
      description: |-
        Example: 
        > Authorization: Bearer <token>
security:
  - JWTAuth: []
tags:
  - name: psps
    description: Collection di risorse di tipo "PSP"
  - name: canali-versamento
    description: Collection di risorse di tipo "Canali Versamento di un PSP"